#pragma once

#include "qram_branch_qutrit.h"

namespace qram_simulator {
	namespace qram_qutrit {
		/**
		 * @brief Branch-based sparse simulator of the QRAM loading circuit (qutrit architecture).
		 *
		 * Every tree node is a three-level system (qutrit): address level addr ∈ {W, L, R} and
		 * data level data ∈ {0, 1}. SubBranch trajectories are evolved along the noisy
		 * operation sequence, with support for good/bad branch pruning and output-sampling fidelity evaluation.
		 *
		 * The typical workflow matches qram_qubit::QRAMCircuit: construct → set memory →
		 * set noise → set_input_* → run_normal / run_full →
		 * sample_and_get_fidelity.
		 *
		 * @note run(version) requires a non-empty noise model to be set first; for noise-free
		 * scenarios call run_normal / run_full directly (this should be handled outside QRAMCircuit).
		 */
		struct QRAMCircuit {
			using qram_state_t = typename SubBranch::element_type;

		public:
			/// Address width (depth of the data tree)
			size_t address_size;
			/// Data width (number of bits per memory slot)
			size_t data_size;
			/// Timing and noise scheduler
			TimeStep time_step;
			/// Data tree: memory[i] is the data_size-bit integer stored at address i
			memory_t memory;

			/* Internal operations */
			/// Noisy operation sequence actually executed (generated by initialize_system)
			TimeSlices operations;

			/// Noise model: {operation type: occurrence probability}
			noise_t noise_parameters;

			/// All branches (trajectories after normalization and disentanglement)
			std::vector<Branch> branches;

			/// Probabilities of all branches (used for sampling and Damping noise evaluation)
			std::vector<double> branch_probs;

			/// View of the branches to be evolved in this run.
			/// version: "full" all branches; "normal" first good branch + all bad branches;
			/// "fast" no branches to evolve (short-circuit computation)
			std::vector<Branch*> valid_branch_view;

			/// Index of the first good branch (serves as the prediction reference for the other good branches); -1 if none
			int64_t first_good_branch = -1;

			/// Indices of the remaining good branches besides the reference
			std::vector<size_t> good_branch_ids;

		public:
			/// Final system state obtained from sampling
			qram_state_t final_system_state;

			/**
			 * @brief Constructs the QRAM circuit (memory uninitialized).
			 * @param address_sz Address width
			 * @param data_sz Data width
			 */
			QRAMCircuit(size_t address_sz, size_t data_sz)
				: address_size(address_sz), data_size(data_sz),
				time_step(address_sz, data_sz)
			{
				memory.resize(pow2(address_size));
			}
			/**
			 * @brief Constructs the QRAM circuit and initializes it with the given data tree (copy).
			 * @param address_sz Address width
			 * @param data_sz Data width
			 * @param memory_ Data tree (length must be 2^address_sz)
			 */
			QRAMCircuit(size_t address_sz, size_t data_sz, const memory_t& memory_)
				: address_size(address_sz), data_size(data_sz),
				time_step(address_sz, data_sz)
			{
				memory.resize(pow2(address_size));
				set_memory(memory_);
			}
			/**
			 * @brief Constructs the QRAM circuit and initializes it with the given data tree (move).
			 * @param address_sz Address width
			 * @param data_sz Data width
			 * @param memory_ Data tree (rvalue)
			 */
			QRAMCircuit(size_t address_sz, size_t data_sz, memory_t&& memory_)
				: address_size(address_sz), data_size(data_sz),
				time_step(address_sz, data_sz)
			{
				memory.resize(pow2(address_size));
				set_memory(std::move(memory_));
			}

			/// Number of physical qubits occupied by the circuit: 2 * (2^address_size - 1)
			inline size_t get_qubit_num() const { return 2 * (pow2(address_size) - 1); }
			/// Total number of memory slots
			inline size_t memory_size() const { return memory.size(); }

			/// Randomly fills the entire data tree using the global random engine
			virtual void set_memory_random();
			/// Sets the data tree (copy)
			virtual void set_memory(const memory_t& new_memory);
			/// Sets the data tree (move)
			virtual void set_memory(memory_t&& new_memory);
			/// Returns a reference to the data tree
			inline auto& get_memory() { return memory; }
			/// Returns a const reference to the data tree
			inline auto& get_memory() const { return memory; }

			/// Returns all branches (const)
			inline auto& get_branches() const { return branches; }
			/// Returns all branches
			inline auto& get_branches() { return branches; }
			/// Returns all branch probabilities (const)
			inline auto& get_branch_probs() const { return branch_probs; }
			/// Returns all branch probabilities
			inline auto& get_branch_probs() { return branch_probs; }
			/// Returns the noisy operation sequence (const)
			inline auto& get_operations() const { return operations; }
			/// Returns the noisy operation sequence
			inline auto& get_operations() { return operations; }

			/**
			 * @brief Sets the noise model.
			 *
			 * Probability parameters are range-checked: all probabilities must lie in [0,1]; Damping additionally
			 * requires gamma < 1 (gamma = 1 would extinguish all excitations in a single step, zeroing the trajectory norm
			 * and breaking sample_output / normalization); out-of-range values throw std::runtime_error.
			 * @param noises A {operation type: occurrence probability} map
			 */
			inline void set_noise_models(const noise_t& noises)
			{
				for (auto& [type, p] : noises)
				{
					if (!(p >= 0.0 && p <= 1.0) ||
						(type == OperationType::Damping && p >= 1.0))
						throw std::runtime_error(
							"set_noise_models: noise probability out of range "
							"(must be in [0,1]; Damping requires gamma < 1)");
				}
				noise_parameters = noises;
			}
			/// Returns the current noise model
			inline auto& get_noise_models() { return noise_parameters; }
			/// Returns the current noise model (const)
			inline auto& get_noise_models() const { return noise_parameters; }
			/// Whether no noise is currently set
			inline bool is_noise_free() const { return noise_parameters.size() == 0; }
			/// Whether the noise model contains Damping
			inline bool has_damping() const { return noise_parameters.find(OperationType::Damping) != noise_parameters.end(); }

			/**
			 * @brief Generates the noisy operation sequence and initializes the branch structure (called internally by the run series).
			 */
			void initialize_system();

			/// Randomly samples n input branches and randomly fills the branch probabilities
			void set_input_random(size_t n_inputs);

			/// Randomly samples n input branches with equal input probability each
			void set_input_uniform(size_t n_inputs);

			/**
			 * @brief Samples an output branch and computes the loading fidelity |<ideal|actual>|^2.
			 * @return The fidelity under the sampled trajectory
			 */
			double sample_and_get_fidelity();

			/**
			 * @brief Preparation phase of a pruned run (called internally by run_normal).
			 *
			 * 1. Builds valid_branch_view (including only the branches to be evolved)
			 * 2. Determines first_good_branch (the prediction reference)
			 * 3. Marks branches[i].good and sets its bus output
			 * 4. Collects good_branch_ids
			 */
			void pick_good_bad();

			/**
			 * @brief Preparation phase of an unpruned run (called internally by run_full).
			 *
			 * Builds valid_branch_view (including all branches).
			 */
			void pick_all();

			/* Execution of operations */
			/// Executes the address copy operation: nodes at layer layer write direction a
			void run_acopy(int layer);
			/// Executes the plain swap at layer layer_id
			void run_swap(size_t layer_id);
			/// Executes the controlled swap at layer layer_id
			void run_cswap(size_t layer_id);
			/// Executes a bit flip on qubit qubit_id (noise)
			void run_bitflip(size_t qubit_id);
			/// Executes a phase flip on qubit qubit_id (noise; depol_id is an associated parameter)
			void run_phaseflip(size_t qubit_id, double depol_id);
			/// Executes a combined bit-phase flip on qubit qubit_id (noise)
			void run_bitphaseflip(size_t qubit_id);
			/// Executes depolarizing on qubit qubit_id (noise)
			void run_depolarizing(size_t qubit_id, double depol_id);
			/// Executes the Hadamard transform on the bus
			void run_hadamard();
			/// Fetches bit digit from the data tree to the bus (FetchData)
			void run_fetchdata(size_t digit);
			/// Bus input of bit digit
			void run_busin(size_t digit);
			/// Bus output of bit digit
			void run_busout(size_t digit);
			/// Full amplitude damping on the given qubit (noise; gamma is the decay rate)
			void run_damp_full(size_t qubit_id, size_t step, double gamma);
			/// System-wide common amplitude damping (noise)
			void run_damp_common(double gamma);

			/// Cleans up sparse elements with zero amplitude
			void clear_zero_elements();

			/// Normalization factor under the current noise model (including Damping)
			double get_normalization_factor() const;
			/// Normalization factor without Damping
			double get_normalization_factor_without_damping() const;
			/// Normalization factor with Damping
			double get_normalization_factor_with_damping() const;
			/// Normalizes all branch amplitudes under the current noise model
			void normalization();
			/// Normalization without Damping
			void normalization_without_damping();
			/// Normalization with Damping
			void normalization_with_damping();

			/// Output sampling (internal variant that skips normalization)
			void sample_output_without_normalization();
			/// Output sampling (internal variant with Damping that skips normalization)
			void sample_output_without_normalization_with_damping();
			/// Output sampling (internal variant without Damping that skips normalization)
			void sample_output_without_normalization_without_damping();
			/// Samples an output bus state according to branch_probs (path without Damping)
			void sample_output();

			/// Marks good branches and determines the prediction reference (run precondition)
			void run_good();
			/// Evolves the branches in valid_branch_view (the actual execution core of the run series)
			void run_valid_branches();

			/// Pruned run: fully simulate bad branches + one good branch as reference (the everyday default entry)
			void run_normal();

			/// Runs all branches without pruning (for debugging, helps verify run())
			void run_full();

			/// Runs good branches only (currently unimplemented)
			void run_good_only();
			/// Runs good branches only (variant without Damping, currently unimplemented)
			void run_good_only_without_damping();
			/// Runs good branches only (variant with Damping, currently unimplemented)
			void run_good_only_with_damping();
			/**
			 * @brief Runs according to a version string.
			 *
			 * Returns immediately when there are no input branches; throws an invalid-input exception
			 * when no noise is set (noise-free scenarios should be handled outside QRAMCircuit).
			 * @param version "full"/"old": no pruning; "new"/"normal": pruning;
			 *                anything else throws an invalid-input exception
			 */
			void run(const std::string& version);

			/// Returns a circuit summary string
			std::string to_string() const;
			/// Returns the full info string including branch details
			std::string to_string_full_info() const;

			/// Version string constant for run(version="full")
			static constexpr auto FULL_VER = "full";
			/// Version string constant for run(version="normal")
			static constexpr auto NORMAL_VER = "normal";

			virtual ~QRAMCircuit() {}
		};
	} // namespace qram_qutrit

	// using QRAMCircuit = qram_qutrit::QRAMCircuit;

}
