#pragma once

#include "qram_branch_qubit.h"

namespace qram_simulator {
	namespace qram_qubit {
		/**
		 * @brief Branch-based sparse simulator of the QRAM loading circuit (qubit architecture).
		 *
		 * Uses (address, bus_input) input branches as trajectory carriers and evolves sparse
		 * SystemState along the noisy operation sequence generated by TimeStep; via good/bad branch
		 * pruning it compresses the simulation scale from all branches down to "fully simulate bad branches + one good branch as reference".
		 *
		 * Typical workflow:
		 * 1. Construct the circuit and set the data tree (set_memory_random / set_memory)
		 * 2. Optionally inject noise (set_noise_models)
		 * 3. Sample input branches (set_input_random / set_input_uniform)
		 * 4. Run (run_normal pruned / run_full unpruned reference)
		 * 5. Sample the output and read the fidelity (sample_and_get_fidelity)
		 */
		struct QRAMCircuit
		{
			using SystemState = typename Branch::state_type;
			using qram_state_t = typename SystemState::element_type;

		public:
			/// Address width (depth of the data tree)
			size_t addr_size;
			/// Data width (number of bits per memory slot)
			size_t data_size;
			/// Timing and noise scheduler (generate produces the noisy operation sequence)
			TimeStep time_step;
			/// Data tree: memory[i] is the data_size-bit integer stored at address i
			memory_t memory;

			/* Internal operations */
			/// Raw operation sequence before noise injection (for debugging)
			TimeSlices raw_operations;
			/// Noisy operation sequence actually executed (generated by initialize_system)
			TimeSlices operations;
			/// Noise model: {operation type: occurrence probability}
			noise_t noise_parameters;

			/// All branch groups (one BranchGroup per address)
			std::vector<BranchGroup> branch_groups;
			/// View of the branch groups to be evolved in this run (after pruning)
			std::vector<BranchGroup*> valid_branch_group_view;
			/// Index of the first good branch group (serves as the prediction reference for the other good branches); -1 if none
			ptrdiff_t first_good_branch_group = -1;
			/// Indices of the remaining good branch groups besides the reference
			std::vector<size_t> good_branch_group_ids;

		public:
			/// Total probability of the sampled output branches (for normalization checks)
			double total_prob = 0;
			/// Final system state obtained from sampling
			qram_state_t final_system_state;

			/**
			 * @brief Constructs the QRAM circuit (memory uninitialized).
			 * @param address_sz Address width
			 * @param data_sz Data width
			 */
			QRAMCircuit(size_t address_sz, size_t data_sz);
			/**
			 * @brief Constructs the QRAM circuit and initializes it with the given data tree.
			 * @param address_sz Address width
			 * @param data_sz Data width
			 * @param memory Data tree (length must be 2^address_sz)
			 */
			QRAMCircuit(size_t address_sz, size_t data_sz, memory_t&& memory);

			/// Randomly fills the entire data tree using the global random engine
			inline void set_memory_random() { random_memory(memory, data_size); }
			/// Sets the data tree (copy)
			void set_memory(const memory_t& new_memory);
			/// Sets the data tree (move)
			void set_memory(memory_t&& new_memory);
			/// Returns a reference to the data tree
			inline auto& get_memory() { return memory; }
			/// Returns a const reference to the data tree
			inline auto& get_memory() const { return memory; }

			/// Number of physical qubits occupied by the circuit: 2 * (2^addr_size - 1)
			inline size_t get_qubit_num() const { return 2 * (pow2(addr_size) - 1); }
			/// Total number of memory slots
			inline size_t memory_size() const { return memory.size(); }

			/**
			 * @brief Injects branch groups directly (for state_manipulator / tests; see init_state).
			 * @param branch_groups_ Branch group collection
			 */
			inline void set_branches(const std::vector<BranchGroup>& branch_groups_) { branch_groups = branch_groups_; }
			/// @overload
			inline void set_branches(std::vector<BranchGroup>&& branch_groups_) { branch_groups = std::move(branch_groups_); }

			/**
			 * @brief Samples n (addr, bus) input branches to fill branch_groups.
			 *
			 * The input probabilities of the branches are normalized together at the end.
			 * @param n_inputs Number of input branches to sample
			 * @param uniform true: every branch has equal input probability; false: input probability ~ U(0,1)
			 */
			void _set_input_impl(size_t n_inputs, bool uniform);
			/// Randomly samples n input branches with input probability ~ U(0,1), then normalizes
			inline void set_input_random(size_t n_inputs) { _set_input_impl(n_inputs, false); }
			/// Randomly samples n input branches with equal input probability each
			inline void set_input_uniform(size_t n_inputs) { _set_input_impl(n_inputs, true); }

			/// Returns all branch groups (const)
			inline auto& get_branch_groups() const { return branch_groups; }
			/// Returns the noisy operation sequence actually executed (const)
			inline auto& get_operations() const { return operations; }
			/// Returns all branch groups
			inline auto& get_branch_groups() { return branch_groups; }
			/// Returns the noisy operation sequence actually executed
			inline auto& get_operations() { return operations; }

			/// @deprecated Clears the noise model; use set_noise_models instead
			[[deprecated]] inline void clear_noise() { noise_parameters.clear(); }

			/// @deprecated Appends a single noise entry; use set_noise_models to set all at once instead
			[[deprecated]] inline void add_noise_model(OperationType t, double v) {
				noise_parameters[t] = v;
			}

			/**
			 * @brief Sets the noise model.
			 *
			 * Probability parameters are range-checked: all probabilities must lie in [0,1]; Damping additionally
			 * requires gamma < 1 (gamma = 1 would extinguish all excitations in a single step, zeroing the trajectory norm
			 * and breaking sample_output / normalization); out-of-range values throw std::runtime_error.
			 * @param noises A {operation type: occurrence probability} map
			 */
			inline void set_noise_models(const std::map<OperationType, double>& noises) {
				for (auto& [type, p] : noises)
				{
					if (!(p >= 0.0 && p <= 1.0) ||
						(type == OperationType::Damping && p >= 1.0))
						throw std::runtime_error(
							"set_noise_models: noise probability out of range "
							"(must be in [0,1]; Damping requires gamma < 1)");
				}
				noise_parameters = noises;
			}

			/// Whether no noise is currently set
			inline bool is_noise_free() const { return noise_parameters.size() == 0; }
			/// Whether the noise model contains Damping
			inline bool has_damping() const { return noise_parameters.find(OperationType::Damping) != noise_parameters.end(); }

			/**
			 * @brief Generates the noisy operation sequence and resets all branch groups.
			 *
			 * The operation sequence is generated via time_step.generate(noise_parameters, arch_qubit),
			 * which also clears the good branch indices and the valid branch view (called internally by the run series).
			 */
			void initialize_system();

			/**
			 * @brief Samples an output branch and computes the loading fidelity |<ideal|actual>|^2.
			 * @return The fidelity under the sampled trajectory; returns 0 when there are no branches
			 */
			double sample_and_get_fidelity();
			/// Alias of sample_and_get_fidelity
			double get_fidelity() { return sample_and_get_fidelity(); }

			/**
			 * @brief Preparation phase of a pruned run (called internally by run()).
			 *
			 * 1. Builds valid_branch_group_view (including only the branch groups to be evolved)
			 * 2. Determines first_good_branch_group (the prediction reference)
			 * 3. Marks branches[i].good and sets its bus output
			 * 4. Collects good_branch_group_ids
			 */
			void prepare_bad();

			/**
			 * @brief Preparation phase of an unpruned run (called internally by run_all()).
			 *
			 * Builds valid_branch_group_view (including all branch groups).
			 */
			void prepare_all();

			/**
			 * @brief Preparation phase of a good-branches-only run (called internally by run_good_only()).
			 *
			 * 1. Builds the good_only valid_branch_group_view
			 * 2. Determines first_good_branch_group
			 * 3. Marks branches[i].good and sets its bus output
			 * 4. Collects good_branch_group_ids
			 */
			void prepare_good_only();

			/* Execution of operations */
			/// Executes the address copy operation: nodes at layer layer write direction a
			void run_acopy(int layer);
			/// Executes the plain swap at layer layer_id
			void run_swap(size_t layer_id);
			/// Executes the controlled swap at layer layer_id
			void run_cswap(size_t layer_id);
			/// Executes a bit flip on qubit qubit_id (noise)
			void run_bitflip(size_t qubit_id);
			/// Executes a phase flip on qubit qubit_id (noise; depol_id is an associated parameter)
			void run_phaseflip(size_t qubit_id, double depol_id);
			/// Executes a combined bit-phase flip on qubit qubit_id (noise)
			void run_bitphaseflip(size_t qubit_id);
			/// Executes depolarizing on qubit qubit_id (noise)
			void run_depolarizing(size_t qubit_id, double depol_id);
			/// Executes the Hadamard transform on the bus
			void run_hadamard();
			/// Fetches bit digit from the data tree to the bus (FetchData)
			void run_fetchdata(size_t digit);
			/// Bus input of bit digit
			void run_busin(size_t digit);
			/// Bus output of bit digit
			void run_busout(size_t digit);
			/// Full amplitude damping on the given qubit (noise; gamma is the decay rate)
			void run_damp_full(size_t qubit_id, size_t step, double gamma);
			/// System-wide common amplitude damping (noise; multiplies the damping factor by the non-zero element count)
			void run_damp_common(double gamma);

			/// Cleans up sparse elements with zero amplitude
			void clear_zero_elements();

			/// Returns a circuit summary string
			std::string to_string() const;
			/// Returns the full info string including branch details
			std::string to_string_full_info() const;

			/// Normalization factor without Damping
			double get_normalization_factor() const;
			/// Normalization factor with Damping
			double get_normalization_factor_with_damping() const;
			/// Normalizes all branch amplitudes under the current noise model
			void normalization();

			/// Materializes the reference good branch's system states for the remaining good branches (XOR mirror prediction)
			void materialize_good_branches();

			/**
			 * @brief Samples an output bus state according to branch_probs.
			 *
			 * The sampled result is written to each branch group and to final_system_state;
			 * the subsequent sample_and_get_fidelity computes the fidelity on that sampled trajectory.
			 */
			void sample_output();

			/// @deprecated Use fmt::format("{}", memory) instead
			[[deprecated]] inline std::string mem_to_string() const {
				return fmt::format("{}", memory);
			}

			/// Evolves good branches only (internal debugging entry)
			void run_good();
			/// Evolves the branches in valid_branch_group_view (the actual execution core of the run series)
			void run_bad();

			/// Generates the operation sequence and runs in pruned mode (equivalent to run_normal)
			void run();

			/// Runs all branches without pruning (plain version for debugging, helps verify run())
			void run_all();

			/// Runs good branches only (plain version for debugging, helps verify run())
			void run_good_only();

			/// Runs all branches without pruning: the unpruned ground-truth reference
			void run_full();

			/// Pruned run: fully simulate bad branches + one good branch as reference (the everyday default entry)
			void run_normal();

			/// Version string constant for run(version="full")
			static constexpr auto FULL_VER = "full";
			/// Version string constant for run(version="normal")
			static constexpr auto NORMAL_VER = "normal";

			/**
			 * @brief Runs according to a version string.
			 * @param version "full"/"old": no pruning; "normal"/"new": pruning;
			 *                "fast": good branches only; anything else throws an invalid-input exception
			 */
			void run(std::string version);
		};
	} // namespace qram_qubit
} // namespace qram_simulator
