# Shared Sphinx configuration for both language trees (zh/ and en/).
#
# Each language tree (source/zh/conf.py, source/en/conf.py) imports every
# name from this module via ``from _conf_base import *`` and then overrides
# the language-specific bits (``language``, ``html_title``).
#
# Layout:
#   docs/sphinx/source/
#   ├── _conf_base.py          <- this file
#   ├── _shared/_static/       <- shared static files (copied into each build)
#   ├── _shared/_templates/    <- shared templates (language switcher, etc.)
#   ├── api_stubs/             <- pybind11-stubgen output (CI-injected, gitignored)
#   ├── zh/                    <- Chinese source tree (conf.py + documents)
#   └── en/                    <- English source tree (conf.py + documents)

from __future__ import annotations

from pathlib import Path

# -- Project information -----------------------------------------------------

project = "QRAM-Simulator"
copyright = "2021-2026, IAI-USTC-Quantum"
author = "IAI-USTC-Quantum"
release = "0.2.0"

# -- Path anchors --------------------------------------------------------------

_SOURCE_ROOT = Path(__file__).resolve().parent  # docs/sphinx/source/
_SHARED = _SOURCE_ROOT / "_shared"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "myst_parser",
    "sphinx_copybutton",
    "breathe",
]

templates_path = [str(_SHARED / "_templates")]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_static_path = [str(_SHARED / "_static")]

# Theme options for furo (same visual style as the SparQSim docs)
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#2563eb",
        "color-brand-content": "#1d4ed8",
    },
    "dark_css_variables": {
        "color-brand-primary": "#3b82f6",
        "color-brand-content": "#60a5fa",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "source_repository": "https://github.com/IAI-USTC-Quantum/QRAM-Simulator/",
    "source_branch": "main",
    "source_directory": "docs/sphinx/source/",
}

# Language switcher in the sidebar (see _shared/_templates/sidebar/langswitch.html)
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/langswitch.html",
        "sidebar/search.html",
        "sidebar/navigation.html",
    ],
}

# -- Options for MyST parser -------------------------------------------------
# https://myst-parser.readthedocs.io/en/latest/configuration.html

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "tasklist",
]

# Generate GitHub-style anchors for h1-h3 so that in-page TOC links
# resolve in both language trees (zh keeps CJK anchors, en gets ASCII ones)
myst_heading_anchors = 3

# -- Options for Breathe (Doxygen C++ API) -----------------------------------
# Doxygen XML is generated beforehand by `doxygen Doxyfile` (done in docs.yml);
# local builds: run doxygen in the repository root first, then make html.

_doxygen_xml = _SOURCE_ROOT.parents[1] / "api" / "xml"

breathe_projects = {"QRAM-Simulator": str(_doxygen_xml)}
breathe_default_project = "QRAM-Simulator"
breathe_domain_by_extension = {
    "h": "cpp",
}

# -- Options for AutoAPI (Python binding API) --------------------------------
# The .pyi stubs are generated by pybind11-stubgen in CI into the shared
# source/api_stubs/ directory (docstrings come from the compiled module and
# are English). Skipped when the directory is absent (local builds without
# an installed binding).

_api_stubs = _SOURCE_ROOT / "api_stubs"
if _api_stubs.exists():
    extensions.append("autoapi.extension")

    autoapi_type = "python"
    autoapi_dirs = [str(_api_stubs)]
    autoapi_root = "api/python"
    autoapi_file_patterns = ["*.pyi", "*.py"]
    autoapi_generate_api_docs = True
    autoapi_add_toctree_entry = True
    autoapi_options = [
        "members",
        "undoc-members",
        "show-inheritance",
        "show-module-summary",
        "imported-members",
    ]
    autoapi_python_class_content = "both"
    autoapi_member_order = "groupwise"
    autoapi_keep_private_level = 0

# -- Options for Intersphinx -------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
}
