var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< qram_simulator::qram_qutrit::QRAMNode >", "structfmt_1_1formatter_3_01qram__simulator_1_1qram__qutrit_1_1QRAMNode_01_4.html", "structfmt_1_1formatter_3_01qram__simulator_1_1qram__qutrit_1_1QRAMNode_01_4" ]
    ] ],
    [ "qram_simulator", "namespaceqram__simulator.html", [
      [ "qram_qubit", "namespaceqram__simulator_1_1qram__qubit.html", [
        [ "Branch", "structqram__simulator_1_1qram__qubit_1_1Branch.html", "structqram__simulator_1_1qram__qubit_1_1Branch" ],
        [ "BranchGroup", "structqram__simulator_1_1qram__qubit_1_1BranchGroup.html", "structqram__simulator_1_1qram__qubit_1_1BranchGroup" ],
        [ "QRAMCircuit", "structqram__simulator_1_1qram__qubit_1_1QRAMCircuit.html", "structqram__simulator_1_1qram__qubit_1_1QRAMCircuit" ],
        [ "State", "structqram__simulator_1_1qram__qubit_1_1State.html", "structqram__simulator_1_1qram__qubit_1_1State" ],
        [ "SystemState", "structqram__simulator_1_1qram__qubit_1_1SystemState.html", "structqram__simulator_1_1qram__qubit_1_1SystemState" ]
      ] ],
      [ "qram_qutrit", "namespaceqram__simulator_1_1qram__qutrit.html", [
        [ "Branch", "structqram__simulator_1_1qram__qutrit_1_1Branch.html", "structqram__simulator_1_1qram__qutrit_1_1Branch" ],
        [ "QRAMCircuit", "structqram__simulator_1_1qram__qutrit_1_1QRAMCircuit.html", "structqram__simulator_1_1qram__qutrit_1_1QRAMCircuit" ],
        [ "QRAMNode", "structqram__simulator_1_1qram__qutrit_1_1QRAMNode.html", "structqram__simulator_1_1qram__qutrit_1_1QRAMNode" ],
        [ "QRAMState", "structqram__simulator_1_1qram__qutrit_1_1QRAMState.html", "structqram__simulator_1_1qram__qutrit_1_1QRAMState" ],
        [ "SubBranch", "structqram__simulator_1_1qram__qutrit_1_1SubBranch.html", "structqram__simulator_1_1qram__qutrit_1_1SubBranch" ]
      ] ],
      [ "Add_ConstUInt", "structqram__simulator_1_1Add__ConstUInt.html", "structqram__simulator_1_1Add__ConstUInt" ],
      [ "Add_Mult_UInt_ConstUInt", "structqram__simulator_1_1Add__Mult__UInt__ConstUInt.html", "structqram__simulator_1_1Add__Mult__UInt__ConstUInt" ],
      [ "Add_UInt_ConstUInt", "structqram__simulator_1_1Add__UInt__ConstUInt.html", "structqram__simulator_1_1Add__UInt__ConstUInt" ],
      [ "Add_UInt_UInt", "structqram__simulator_1_1Add__UInt__UInt.html", "structqram__simulator_1_1Add__UInt__UInt" ],
      [ "Add_UInt_UInt_InPlace", "structqram__simulator_1_1Add__UInt__UInt__InPlace.html", "structqram__simulator_1_1Add__UInt__UInt__InPlace" ],
      [ "AddAssign_AnyInt_AnyInt", "structqram__simulator_1_1AddAssign__AnyInt__AnyInt.html", "structqram__simulator_1_1AddAssign__AnyInt__AnyInt" ],
      [ "AddRegister", "structqram__simulator_1_1AddRegister.html", "structqram__simulator_1_1AddRegister" ],
      [ "AddRegisterWithHadamard", "structqram__simulator_1_1AddRegisterWithHadamard.html", "structqram__simulator_1_1AddRegisterWithHadamard" ],
      [ "Assign", "structqram__simulator_1_1Assign.html", "structqram__simulator_1_1Assign" ],
      [ "BaseOperator", "structqram__simulator_1_1BaseOperator.html", "structqram__simulator_1_1BaseOperator" ],
      [ "CheckDuplicateKey", "structqram__simulator_1_1CheckDuplicateKey.html", "structqram__simulator_1_1CheckDuplicateKey" ],
      [ "CheckNan", "structqram__simulator_1_1CheckNan.html", "structqram__simulator_1_1CheckNan" ],
      [ "CheckNormalization", "structqram__simulator_1_1CheckNormalization.html", "structqram__simulator_1_1CheckNormalization" ],
      [ "CheckNormalization_Renormalize", "structqram__simulator_1_1CheckNormalization__Renormalize.html", "structqram__simulator_1_1CheckNormalization__Renormalize" ],
      [ "ClearZero", "structqram__simulator_1_1ClearZero.html", "structqram__simulator_1_1ClearZero" ],
      [ "CombineRegister", "structqram__simulator_1_1CombineRegister.html", "structqram__simulator_1_1CombineRegister" ],
      [ "Compare_UInt_UInt", "structqram__simulator_1_1Compare__UInt__UInt.html", "structqram__simulator_1_1Compare__UInt__UInt" ],
      [ "CondRot_General_Bool", "structqram__simulator_1_1CondRot__General__Bool.html", "structqram__simulator_1_1CondRot__General__Bool" ],
      [ "CondRot_Rational_Bool", "structqram__simulator_1_1CondRot__Rational__Bool.html", "structqram__simulator_1_1CondRot__Rational__Bool" ],
      [ "ContinuousRange", "structqram__simulator_1_1ContinuousRange.html", "structqram__simulator_1_1ContinuousRange" ],
      [ "CustomArithmetic", "structqram__simulator_1_1CustomArithmetic.html", "structqram__simulator_1_1CustomArithmetic" ],
      [ "Div_Sqrt_Arccos_Int_Int", "structqram__simulator_1_1Div__Sqrt__Arccos__Int__Int.html", "structqram__simulator_1_1Div__Sqrt__Arccos__Int__Int" ],
      [ "FlipBools", "structqram__simulator_1_1FlipBools.html", "structqram__simulator_1_1FlipBools" ],
      [ "GateBase", "structqram__simulator_1_1GateBase.html", "structqram__simulator_1_1GateBase" ],
      [ "GetMid_UInt_UInt", "structqram__simulator_1_1GetMid__UInt__UInt.html", "structqram__simulator_1_1GetMid__UInt__UInt" ],
      [ "GetRotateAngle_Int_Int", "structqram__simulator_1_1GetRotateAngle__Int__Int.html", "structqram__simulator_1_1GetRotateAngle__Int__Int" ],
      [ "GlobalPhase_Int", "structqram__simulator_1_1GlobalPhase__Int.html", "structqram__simulator_1_1GlobalPhase__Int" ],
      [ "Hadamard_Bool", "structqram__simulator_1_1Hadamard__Bool.html", "structqram__simulator_1_1Hadamard__Bool" ],
      [ "Hadamard_Int", "structqram__simulator_1_1Hadamard__Int.html", "structqram__simulator_1_1Hadamard__Int" ],
      [ "Hadamard_Int_Full", "structqram__simulator_1_1Hadamard__Int__Full.html", "structqram__simulator_1_1Hadamard__Int__Full" ],
      [ "Hadamard_PartialQubit", "structqram__simulator_1_1Hadamard__PartialQubit.html", "structqram__simulator_1_1Hadamard__PartialQubit" ],
      [ "Init_Unsafe", "structqram__simulator_1_1Init__Unsafe.html", "structqram__simulator_1_1Init__Unsafe" ],
      [ "inverseQFT", "structqram__simulator_1_1inverseQFT.html", "structqram__simulator_1_1inverseQFT" ],
      [ "Less_UInt_UInt", "structqram__simulator_1_1Less__UInt__UInt.html", "structqram__simulator_1_1Less__UInt__UInt" ],
      [ "ModuleInheritance_Test", "structqram__simulator_1_1ModuleInheritance__Test.html", "structqram__simulator_1_1ModuleInheritance__Test" ],
      [ "ModuleInheritance_Test_SelfAdjoint", "structqram__simulator_1_1ModuleInheritance__Test__SelfAdjoint.html", "structqram__simulator_1_1ModuleInheritance__Test__SelfAdjoint" ],
      [ "MoveBackRegister", "structqram__simulator_1_1MoveBackRegister.html", "structqram__simulator_1_1MoveBackRegister" ],
      [ "Mult_UInt_ConstUInt", "structqram__simulator_1_1Mult__UInt__ConstUInt.html", "structqram__simulator_1_1Mult__UInt__ConstUInt" ],
      [ "Normalize", "structqram__simulator_1_1Normalize.html", "structqram__simulator_1_1Normalize" ],
      [ "Operation", "structqram__simulator_1_1Operation.html", "structqram__simulator_1_1Operation" ],
      [ "OperationPack", "structqram__simulator_1_1OperationPack.html", "structqram__simulator_1_1OperationPack" ],
      [ "PartialTrace", "structqram__simulator_1_1PartialTrace.html", "structqram__simulator_1_1PartialTrace" ],
      [ "PartialTraceSelect", "structqram__simulator_1_1PartialTraceSelect.html", "structqram__simulator_1_1PartialTraceSelect" ],
      [ "PartialTraceSelectRange", "structqram__simulator_1_1PartialTraceSelectRange.html", "structqram__simulator_1_1PartialTraceSelectRange" ],
      [ "Phase_Bool", "structqram__simulator_1_1Phase__Bool.html", "structqram__simulator_1_1Phase__Bool" ],
      [ "Pop", "structqram__simulator_1_1Pop.html", "structqram__simulator_1_1Pop" ],
      [ "Push", "structqram__simulator_1_1Push.html", "structqram__simulator_1_1Push" ],
      [ "QFT", "structqram__simulator_1_1QFT.html", "structqram__simulator_1_1QFT" ],
      [ "QFT_Full", "structqram__simulator_1_1QFT__Full.html", "structqram__simulator_1_1QFT__Full" ],
      [ "QRAMInputGenerator", "structqram__simulator_1_1QRAMInputGenerator.html", "structqram__simulator_1_1QRAMInputGenerator" ],
      [ "QRAMLoad", "structqram__simulator_1_1QRAMLoad.html", "structqram__simulator_1_1QRAMLoad" ],
      [ "QRAMLoadFast", "structqram__simulator_1_1QRAMLoadFast.html", "structqram__simulator_1_1QRAMLoadFast" ],
      [ "RangeConditionalPhaseFlip", "structqram__simulator_1_1RangeConditionalPhaseFlip.html", "structqram__simulator_1_1RangeConditionalPhaseFlip" ],
      [ "Reflection_Bool", "structqram__simulator_1_1Reflection__Bool.html", "structqram__simulator_1_1Reflection__Bool" ],
      [ "RemoveRegister", "structqram__simulator_1_1RemoveRegister.html", "structqram__simulator_1_1RemoveRegister" ],
      [ "Rot_Bool", "structqram__simulator_1_1Rot__Bool.html", "structqram__simulator_1_1Rot__Bool" ],
      [ "Rot_GeneralStatePrep", "structqram__simulator_1_1Rot__GeneralStatePrep.html", "structqram__simulator_1_1Rot__GeneralStatePrep" ],
      [ "Rot_GeneralUnitary", "structqram__simulator_1_1Rot__GeneralUnitary.html", "structqram__simulator_1_1Rot__GeneralUnitary" ],
      [ "RXgate_Bool", "structqram__simulator_1_1RXgate__Bool.html", "structqram__simulator_1_1RXgate__Bool" ],
      [ "RYgate_Bool", "structqram__simulator_1_1RYgate__Bool.html", "structqram__simulator_1_1RYgate__Bool" ],
      [ "RZgate_Bool", "structqram__simulator_1_1RZgate__Bool.html", "structqram__simulator_1_1RZgate__Bool" ],
      [ "SelfAdjointOperator", "classqram__simulator_1_1SelfAdjointOperator.html", "classqram__simulator_1_1SelfAdjointOperator" ],
      [ "Sgate_Bool", "structqram__simulator_1_1Sgate__Bool.html", "structqram__simulator_1_1Sgate__Bool" ],
      [ "ShiftLeft", "structqram__simulator_1_1ShiftLeft.html", "structqram__simulator_1_1ShiftLeft" ],
      [ "ShiftRight", "structqram__simulator_1_1ShiftRight.html", "structqram__simulator_1_1ShiftRight" ],
      [ "SortByAmplitude", "structqram__simulator_1_1SortByAmplitude.html", "structqram__simulator_1_1SortByAmplitude" ],
      [ "SortByKey", "structqram__simulator_1_1SortByKey.html", "structqram__simulator_1_1SortByKey" ],
      [ "SortByKey2", "structqram__simulator_1_1SortByKey2.html", "structqram__simulator_1_1SortByKey2" ],
      [ "SortExceptBit", "structqram__simulator_1_1SortExceptBit.html", "structqram__simulator_1_1SortExceptBit" ],
      [ "SortExceptKey", "structqram__simulator_1_1SortExceptKey.html", "structqram__simulator_1_1SortExceptKey" ],
      [ "SortExceptKeyHadamard", "structqram__simulator_1_1SortExceptKeyHadamard.html", "structqram__simulator_1_1SortExceptKeyHadamard" ],
      [ "SortUnconditional", "structqram__simulator_1_1SortUnconditional.html", "structqram__simulator_1_1SortUnconditional" ],
      [ "SparseState", "structqram__simulator_1_1SparseState.html", "structqram__simulator_1_1SparseState" ],
      [ "SplitRegister", "structqram__simulator_1_1SplitRegister.html", "structqram__simulator_1_1SplitRegister" ],
      [ "Sqrt_Div_Arccos_Int_Int", "structqram__simulator_1_1Sqrt__Div__Arccos__Int__Int.html", "structqram__simulator_1_1Sqrt__Div__Arccos__Int__Int" ],
      [ "StateEqualExceptKey", "structqram__simulator_1_1StateEqualExceptKey.html", "structqram__simulator_1_1StateEqualExceptKey" ],
      [ "StateEqualExceptQubits", "structqram__simulator_1_1StateEqualExceptQubits.html", "structqram__simulator_1_1StateEqualExceptQubits" ],
      [ "StateHashExceptKey", "structqram__simulator_1_1StateHashExceptKey.html", "structqram__simulator_1_1StateHashExceptKey" ],
      [ "StateHashExceptQubits", "structqram__simulator_1_1StateHashExceptQubits.html", "structqram__simulator_1_1StateHashExceptQubits" ],
      [ "StateLessExceptKey", "structqram__simulator_1_1StateLessExceptKey.html", "structqram__simulator_1_1StateLessExceptKey" ],
      [ "StateLessExceptQubits", "structqram__simulator_1_1StateLessExceptQubits.html", "structqram__simulator_1_1StateLessExceptQubits" ],
      [ "StateLoad", "structqram__simulator_1_1StateLoad.html", "structqram__simulator_1_1StateLoad" ],
      [ "StatePrint", "structqram__simulator_1_1StatePrint.html", "structqram__simulator_1_1StatePrint" ],
      [ "StateStorage", "structqram__simulator_1_1StateStorage.html", "structqram__simulator_1_1StateStorage" ],
      [ "Swap_Bool_Bool", "structqram__simulator_1_1Swap__Bool__Bool.html", "structqram__simulator_1_1Swap__Bool__Bool" ],
      [ "Swap_General_General", "structqram__simulator_1_1Swap__General__General.html", "structqram__simulator_1_1Swap__General__General" ],
      [ "SXgate_Bool", "structqram__simulator_1_1SXgate__Bool.html", "structqram__simulator_1_1SXgate__Bool" ],
      [ "System", "structqram__simulator_1_1System.html", "structqram__simulator_1_1System" ],
      [ "TestRemovable", "structqram__simulator_1_1TestRemovable.html", "structqram__simulator_1_1TestRemovable" ],
      [ "Tgate_Bool", "structqram__simulator_1_1Tgate__Bool.html", "structqram__simulator_1_1Tgate__Bool" ],
      [ "TimeSlices", "structqram__simulator_1_1TimeSlices.html", "structqram__simulator_1_1TimeSlices" ],
      [ "TimeStep", "structqram__simulator_1_1TimeStep.html", "structqram__simulator_1_1TimeStep" ],
      [ "U2gate_Bool", "structqram__simulator_1_1U2gate__Bool.html", "structqram__simulator_1_1U2gate__Bool" ],
      [ "U3gate_Bool", "structqram__simulator_1_1U3gate__Bool.html", "structqram__simulator_1_1U3gate__Bool" ],
      [ "ViewNormalization", "structqram__simulator_1_1ViewNormalization.html", "structqram__simulator_1_1ViewNormalization" ],
      [ "Xgate_Bool", "structqram__simulator_1_1Xgate__Bool.html", "structqram__simulator_1_1Xgate__Bool" ],
      [ "Ygate_Bool", "structqram__simulator_1_1Ygate__Bool.html", "structqram__simulator_1_1Ygate__Bool" ],
      [ "ZeroConditionalPhaseFlip", "structqram__simulator_1_1ZeroConditionalPhaseFlip.html", "structqram__simulator_1_1ZeroConditionalPhaseFlip" ],
      [ "Zgate_Bool", "structqram__simulator_1_1Zgate__Bool.html", "structqram__simulator_1_1Zgate__Bool" ]
    ] ]
];